// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD69uYn8uN8vPHfgaGetJc61K8l9wmvPnk',
    appId: '1:72214694310:web:45771c18d431637dc7e767',
    messagingSenderId: '72214694310',
    projectId: 'janrakshak-iot',
    authDomain: 'janrakshak-iot.firebaseapp.com',
    databaseURL: 'https://janrakshak-iot-default-rtdb.firebaseio.com',
    storageBucket: 'janrakshak-iot.firebasestorage.app',
    measurementId: 'G-F8H760TBRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMoj10RQQ5C3vY7PVtCGlC7Kq7lHoFbg',
    appId: '1:72214694310:android:a35f4ee6c37915c1c7e767',
    messagingSenderId: '72214694310',
    projectId: 'janrakshak-iot',
    databaseURL: 'https://janrakshak-iot-default-rtdb.firebaseio.com',
    storageBucket: 'janrakshak-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo11IU1uRG7s-sOVwXVMVaE8sl3UmrIPU',
    appId: '1:72214694310:ios:40757f53503e01b5c7e767',
    messagingSenderId: '72214694310',
    projectId: 'janrakshak-iot',
    databaseURL: 'https://janrakshak-iot-default-rtdb.firebaseio.com',
    storageBucket: 'janrakshak-iot.firebasestorage.app',
    iosBundleId: 'com.example.innohack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo11IU1uRG7s-sOVwXVMVaE8sl3UmrIPU',
    appId: '1:72214694310:ios:40757f53503e01b5c7e767',
    messagingSenderId: '72214694310',
    projectId: 'janrakshak-iot',
    databaseURL: 'https://janrakshak-iot-default-rtdb.firebaseio.com',
    storageBucket: 'janrakshak-iot.firebasestorage.app',
    iosBundleId: 'com.example.innohack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD69uYn8uN8vPHfgaGetJc61K8l9wmvPnk',
    appId: '1:72214694310:web:d4549ab21991b9cbc7e767',
    messagingSenderId: '72214694310',
    projectId: 'janrakshak-iot',
    authDomain: 'janrakshak-iot.firebaseapp.com',
    databaseURL: 'https://janrakshak-iot-default-rtdb.firebaseio.com',
    storageBucket: 'janrakshak-iot.firebasestorage.app',
    measurementId: 'G-0VD29YRMV1',
  );
}
